--- bzip2-1.0.6/Makefile	2017-05-25 16:09:05.623861318 -0700
+++ patch-files/Makefile	2017-05-25 16:12:32.190589560 -0700
@@ -21,7 +21,7 @@
 LDFLAGS=
 
 BIGFILES=-D_FILE_OFFSET_BITS=64
-CFLAGS=-Wall -Winline -O2 -g $(BIGFILES)
+CFLAGS=-fPIC -Wall -Winline -O2 -g $(BIGFILES)
 
 # Where you want it installed when you do 'make install'
 PREFIX=/usr/local
