#%Module1.0
module-whatis "R"
module-whatis "Version: VERSION"
module-whatis "Description: R"
prepend-path PATH /opt/R/bin
prepend-path R_LIBS /opt/R/local/lib
set dir ""
if { [ file exists /opt/R/local/lib/mpi ] } {
  set dir [ exec ls /opt/R/local/lib/mpi ]
}
if { [ string compare $dir "" ] && [info exists ::env(MPIHOME)]} {
  foreach {x} [glob -directory /opt/R/local/lib/mpi -tails *] {
    if {[regexp $x $::env(MPIHOME)]} {
      set mpi $x
      break
    }
  }
  if {! [info exists mpi]} {
    if {[ regexp ScaleMP $::env(MPIHOME)]} {
        set mpi vsmp
    }
  }
  if {! [info exists mpi]} {
    puts stderr "No supported MPI flavor found"
    exit 1
  }
  set dir [ exec ls /opt/R/local/lib/mpi/$mpi ]
  if {  [ string compare $dir "" ] } {
    foreach {x} [glob -directory /opt/R/local/lib/mpi/$mpi -tails *] {
      if {[regexp $x $::env(MPIHOME)]} {
        set network $x
        break
      }
    }
  }
  if {! [info exists network]} {
    if {[ regexp ScaleMP $::env(MPIHOME)]} {
       set network ib
    }
  }
  if {! [info exists network]} {
    puts stderr "No supported network found"
    exit 1
  }
  module-whatis "MPI: $mpi $network"
  prepend-path R_LIBS /opt/R/local/lib/mpi/$mpi/$network
}
setenv RHOME /opt/R
