ifndef ROLLCOMPILER
  ROLLCOMPILER = gnu
endif
COMPILERNAME := $(firstword $(subst /, ,$(ROLLCOMPILER)))

NAME           = sdsc-R
VERSION        = 3.4.0
RELEASE        = 0
PKGROOT        = /opt/R

SRC_SUBDIR     = R

SOURCE_NAME    = R
SOURCE_SUFFIX  = tar.gz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

ZLIB_NAME    = zlib
ZLIB_SUFFIX  = tar.gz
ZLIB_VERSION = 1.2.11
ZLIB_PKG     = $(ZLIB_NAME)-$(ZLIB_VERSION).$(ZLIB_SUFFIX)
ZLIB_DIR     = $(ZLIB_PKG:%.$(ZLIB_SUFFIX)=%)

BZIP2_NAME    = bzip2
BZIP2_SUFFIX  = tar.gz
BZIP2_VERSION = 1.0.6
BZIP2_PKG     = $(BZIP2_NAME)-$(BZIP2_VERSION).$(BZIP2_SUFFIX)
BZIP2_DIR     = $(BZIP2_PKG:%.$(BZIP2_SUFFIX)=%)

XZ_NAME    = xz
XZ_SUFFIX  = tar.gz
XZ_VERSION = 5.2.3
XZ_PKG     = $(XZ_NAME)-$(XZ_VERSION).$(XZ_SUFFIX)
XZ_DIR     = $(XZ_PKG:%.$(XZ_SUFFIX)=%)

PCRE_NAME    = pcre
PCRE_SUFFIX  = tar.gz
PCRE_VERSION = 8.38
PCRE_PKG     = $(PCRE_NAME)-$(PCRE_VERSION).$(PCRE_SUFFIX)
PCRE_DIR     = $(PCRE_PKG:%.$(PCRE_SUFFIX)=%)

CURL_NAME    = curl
CURL_SUFFIX  = tar.gz
CURL_VERSION = 7.50.3
CURL_PKG     = $(CURL_NAME)-$(CURL_VERSION).$(CURL_SUFFIX)
CURL_DIR     = $(CURL_PKG:%.$(CURL_SUFFIX)=%)

TAR_GZ_PKGS    = $(SOURCE_PKG) $(ZLIB_PKG) $(BZIP2_PKG) $(XZ_PKG) $(PCRE_PKG) $(CURL_PKG)

RPM.EXTRAS     = AutoReq:No
